"""Safe on-disk storage for uploaded images.

Security properties:
  * filenames are generated server-side (UUID4 hex + extension) — client
    filenames are never used, so path traversal is impossible;
  * every filename is re-validated against a strict pattern before any
    filesystem access (defence in depth);
  * nothing in this module is ever exposed to clients except the bare
    generated filename (never a path).
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from uuid import uuid4

from app.core.exceptions import StorageError

logger = logging.getLogger(__name__)

_ALLOWED_EXTENSIONS = {".jpg", ".png", ".webp"}
_SAFE_FILENAME_RE = re.compile(r"^[0-9a-f]{32}\.(jpg|png|webp)$")


class ImageStorage:
    """Stores image bytes under a private directory."""

    def __init__(self, base_dir: Path) -> None:
        self._base_dir = base_dir

    @property
    def base_dir(self) -> Path:
        return self._base_dir

    def ensure_ready(self) -> None:
        """Create the storage directory if it does not exist (idempotent)."""
        try:
            self._base_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            logger.exception("Could not create upload directory.")
            raise StorageError("The upload directory is not available.") from exc

    def save(self, data: bytes, extension: str) -> str:
        """Write image bytes under a generated filename; return that filename."""
        if extension not in _ALLOWED_EXTENSIONS:
            # Programming error, not user input: never reachable from the API.
            raise ValueError(f"Unsupported storage extension: {extension!r}")

        self.ensure_ready()
        filename = f"{uuid4().hex}{extension}"
        try:
            (self._base_dir / filename).write_bytes(data)
        except OSError as exc:
            logger.exception("Failed to write uploaded image.")
            raise StorageError("The image could not be stored.") from exc
        return filename

    def read_bytes(self, filename: str) -> bytes:
        """Read a stored image back by filename (used by the ML worker)."""
        path = self.path_for(filename)
        try:
            return path.read_bytes()
        except OSError as exc:
            logger.exception("Failed to read stored image.")
            raise StorageError("The stored image could not be read.") from exc

    def path_for(self, filename: str) -> Path:
        """Resolve a stored filename to a path, rejecting anything unsafe."""
        if not _SAFE_FILENAME_RE.fullmatch(filename):
            # Should never happen: filenames are generated by save().
            raise StorageError("The stored image reference is invalid.")
        return self._base_dir / filename
